import os
import datetime # Import the datetime module

def application(environ, start_response):
    # Generate HTML content
    html = """<!DOCTYPE html>
<html>
<head>
    <title>When Bike (on startup)</title>
    <meta charset="utf-8">
</head>
<body>
    <h1>I'm full-stack now :-)</h1>
    <p>Generated by Python!</p>
</body>
</html>"""

    # Convert to bytes
    data = html.encode('utf-8')

    # HTTP response headers
    status = '200 OK'
    response_headers = [
        ('Content-Type', 'text/html'),
        ('Content-Length', str(len(data)))
    ]

    # Debug info - print the current directory
    print(f"Current directory: {os.getcwd()}")

    # Send response
    start_response(status, response_headers)
    return [data]

# For local testing
if __name__ == '__main__':
    # This will only run when the script is executed directly (i.e. not on startup)
    try:
        # Get the directory where the script is located
        script_dir = os.path.dirname(os.path.abspath(__file__))
        # Define the full path for the output HTML file
        output_file_path = os.path.join(script_dir, 'index.html')

        # Get the current date and time
        now = datetime.datetime.now()
        # Format the timestamp
        timestamp_str = now.strftime("%Y-%m-%d %H:%M:%S")

        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>When Bike</title>
</head>
<body>
    <h1>I'm full-stack now :-)</h1>
    <p>Generated by Python!</p>
    <p>File generated on: {timestamp_str}</p>
    <iframe title="Today's weather metrics" aria-label="Multiple Columns" id="datawrapper-chart-aI2gc" src="https://datawrapper.dwcdn.net/aI2gc/3/" scrolling="no" frameborder="0" style="border: none;" width="600" height="927" data-external="1"></iframe>
</body>
</html>"""

        # Write the HTML content to the file in the script's directory
        with open(output_file_path, 'w') as file:
            file.write(html_content)

        print(f"HTML file generated successfully at {timestamp_str} in {script_dir}!")
    except Exception as e:
        print(f"Error generating HTML: {e}")