name: Publish Website to CPanel
on:
  push:
    branches:
      - master
jobs:
  Proof-HTML:
    name: Proof-HTML
    runs-on: ubuntu-latest
    steps:
    - uses: anishathalye/proof-html@v1
      with:
        directory: ./
        enforce_https: false
        check_external_hash: false
        url_ignore_re: |
          ^https://codepen.io
          ^https://www.linkedin.com

  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    needs: Proof-HTML
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Install Git
      run: sudo apt -y install git
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
         server: ${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.ftp_password }}
         protocol: ftps
         port: 21



